name: 	      Shiju Leon
title:        My Blog
markdown:     kramdown
permalink:    /blog/:categories/:year/:month/:day/:title.html
pygments:     true
paginate:     6
paginate_path: "blog/page:num"
baseurl: /blog
